/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/templatemodels/vanillalocalvol/vanillalocalvolmodels.hpp>
#include <ql/experimental/templatemodels/vanillalocalvol/vanillalocalvolmodelT.hpp>

