// THIS FILE IS AUTO-GENERATED BY buildinfo.py
#define GIT_REPO "C:/Users/d91454/workspace/quantlib-old/QuantLib"
#define GIT_BRANCH "localCorrSSch"
#define GIT_COMMIT_ID "708a0d5401b05a5d1739f1b68c7220c215f35e37"
#define GIT_COMMIT_ID_SHORT "708a0d540"
#define GIT_WORKING_DIR_STATUS " buildinfo.hpp"
#define GIT_BUILD_INFO_NOW "2019-03-06 10:59:49.746000"
