
import datetime
from subprocess import Popen, PIPE

git = 'C:\\Program Files\\Git\\bin\\git.exe'

(top_level, err) = Popen([git, 'rev-parse','--show-toplevel'], stdout=PIPE).communicate()
(commit, err) = Popen([git, 'rev-parse','HEAD'], stdout=PIPE).communicate()
(commit_short, err) = Popen([git, 'rev-parse','--short','HEAD'], stdout=PIPE).communicate()
(branch, err) = Popen([git, 'rev-parse','--abbrev-ref','HEAD'], stdout=PIPE).communicate()
(status, err) = Popen([git, 'status','--porcelain'], stdout=PIPE).communicate()
status_string = str(status)[2:-1]

f = open('buildinfo.hpp','w+')
f.write('// THIS FILE IS AUTO-GENERATED BY buildinfo.py\n')
f.write('#define GIT_REPO "'+top_level[:-1].decode('utf-8')+'"\n')
f.write('#define GIT_BRANCH "'+branch[:-1].decode('utf-8')+'"\n')
f.write('#define GIT_COMMIT_ID "'+commit[:-1].decode('utf-8')+'"\n')
f.write('#define GIT_COMMIT_ID_SHORT "'+commit_short[:-1].decode('utf-8')+'"\n')
f.write('#define GIT_WORKING_DIR_STATUS "'+status_string+'"\n')
f.write('#define GIT_BUILD_INFO_NOW "'+str(datetime.datetime.now())+'"\n')
f.close()
