// THIS FILE IS AUTO-GENERATED BY buildinfo.py
#define GIT_REPO "C:/Users/d91454/workspace/quantlib-old/QuantLib"
#define GIT_BRANCH "localCorrSSch"
#define GIT_COMMIT_ID "de01238c3725ce39036125a8de664400e9e29351"
#define GIT_COMMIT_ID_SHORT "de01238c3"
#define GIT_WORKING_DIR_STATUS " buildinfo.hpp"
#define GIT_BUILD_INFO_NOW "2019-02-27 17:37:46.224000"
