// THIS FILE IS AUTO-GENERATED BY buildinfo.py
#define GIT_REPO "C:/Users/d91454/workspace/quantlib-old/QuantLib"
#define GIT_BRANCH "localCorrSSch"
#define GIT_COMMIT_ID "b66ded2e39ac94204d56dd907021ba5b5fa6b3e8"
#define GIT_COMMIT_ID_SHORT "b66ded2e3"
#define GIT_WORKING_DIR_STATUS " buildinfo.hpp"
#define GIT_BUILD_INFO_NOW "2019-02-28 10:55:52.912000"
