/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/templatemodels/multiasset/corrtermstructureStrike.hpp>
#include <ql/experimental/templatemodels/multiasset/localcorrelationbsmodel.hpp>
#include <ql/experimental/templatemodels/multiasset/localcorrelationSLVmodel.hpp>
#include <ql/experimental/templatemodels/multiasset/localcorrsurfaceabf.hpp>
#include <ql/experimental/templatemodels/multiasset/localcorrtermstructure.hpp>
#include <ql/experimental/templatemodels/multiasset/multiassetbsmodel.hpp>
#include <ql/experimental/templatemodels/multiasset/multiassetslvmodel.hpp>

#include <ql/experimental/templatemodels/multiasset/Helper/all.hpp>
#include <ql/experimental/templatemodels/multiasset/localCorrFX/all.hpp>
