/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/templatemodels/multiasset/localCorrFX/CTSlocalInCrossCorrelationFX.hpp>
#include <ql/experimental/templatemodels/multiasset/localCorrFX/CTSlocalInCrossCovarianceFX.hpp>
#include <ql/experimental/templatemodels/multiasset/localCorrFX/CTSlocalInCrossNegSkewFX.hpp>
#include <ql/experimental/templatemodels/multiasset/localCorrFX/CTSlocalInCrossVolatilityFX.hpp>
#include <ql/experimental/templatemodels/multiasset/localCorrFX/localcorrsurfaceabfFX.hpp>

