/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/templatemodels/commodity/commoditymodels.hpp>
#include <ql/experimental/templatemodels/commodity/indextermstructure.hpp>
#include <ql/experimental/templatemodels/commodity/twofactorlognormalmodelT.hpp>
#include <ql/experimental/templatemodels/commodity/twofactormeanreversionmodelT.hpp>
#include <ql/experimental/templatemodels/commodity/twofactornormalmodelT.hpp>

