/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/templatemodels/qgaussian/qgaussiancalibrator.hpp>
#include <ql/experimental/templatemodels/qgaussian/qgswaptionmodelT.hpp>
#include <ql/experimental/templatemodels/qgaussian/quasigaussianmodelabcdT.hpp>
#include <ql/experimental/templatemodels/qgaussian/quasigaussianmodels.hpp>
#include <ql/experimental/templatemodels/qgaussian/quasigaussianmodelT.hpp>

