/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/templatemodels/qgaussian2/mccalibrator.hpp>
#include <ql/experimental/templatemodels/qgaussian2/qgcalibrator.hpp>
#include <ql/experimental/templatemodels/qgaussian2/qglsvmodel.hpp>
#include <ql/experimental/templatemodels/qgaussian2/quasigaussianmodel2T.hpp>
#include <ql/experimental/templatemodels/qgaussian2/qgaverageswapratemodelT.hpp>
#include <ql/experimental/templatemodels/qgaussian2/qglocalvolmodel.hpp>
#include <ql/experimental/templatemodels/qgaussian2/qgswapratemodelT.hpp>

