/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/templatemodels/hybrid/assetmodelT.hpp>
#include <ql/experimental/templatemodels/hybrid/hybridmodels.hpp>
#include <ql/experimental/templatemodels/hybrid/hybridmodelT.hpp>
#include <ql/experimental/templatemodels/hybrid/spreadmodelT.hpp>

