/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/templatemodels/montecarlo/commoditypayoffT.hpp>
#include <ql/experimental/templatemodels/montecarlo/amcpricerT.hpp>
#include <ql/experimental/templatemodels/montecarlo/mcscriptT.hpp>
#include <ql/experimental/templatemodels/montecarlo/montecarlomodells.hpp>
#include <ql/experimental/templatemodels/montecarlo/mcpayoffT.hpp>
#include <ql/experimental/templatemodels/montecarlo/mcsimulationT.hpp>
#include <ql/experimental/templatemodels/montecarlo/ratespayoffT.hpp>

#include <ql/experimental/templatemodels/montecarlo/scripting/all.hpp>
